[build]
publish = "_site"
command = "eleventy"

[context.deploy-preview]
  command = "eleventy && npm run noIndex"

[context.branch-deploy]
  command = "eleventy && npm run noIndex"

[[redirects]]
from = "/search-results"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"

[[redirects]]
from = "/books/:id"
to = "/.netlify/functions/serverless"
status = 200
force = false
_generated_by_eleventy_serverless = "serverless"

[[redirects]]
from = "/images/*"
to = "https://cms.scrinium.nl/assets/:splat"
status = 200
force = true
