[build]
publish = "_site"
command = "eleventy"

[[headers]]
for = "/*"

  [headers.values]
  Cache-Control = "public, s-max-age=604800"

[[headers]]
for = "/images/*"

  [headers.values]
  Cache-Control = "max-age=31536000, immutable"

[[redirects]]
from = "/search-results"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"

[[redirects]]
from = "/book/:id"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"

[[redirects]]
from = "/books/*"
to = "/book/:splat"
status = 200
force = true

[[redirects]]
from = "/images/*"
to = "https://stettik.engelswoord.nl/assets/:splat"
status = 200
force = true
