[build]
publish = "_site"
command = "eleventy"

[[headers]]
for = "/*"

  [headers.values]
  Cache-Control = "public, s-max-age=604800"

[[redirects]]
from = "/search-results"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"

[[redirects]]
from = "/books/:id"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"

[[redirects]]
from = "/images/*"
to = "https://stettik.engelswoord.nl/assets/:splat"
status = 200
force = true
